__author__ = 'andrey.samokhvalov21@yandex.ru'

CHART_DATA_PERIODS = [300, 900, 1800, 7200, 14400, 86400]

# Pulled from var currencyPairArray on https://poloniex.com/exchange
# Current as of Sun May 7 07:11:23 UTC 2017
CURRENCY_PAIRS = [
    "BTC_AMP",
    "BTC_ARDR",
    "BTC_BCN",
    "BTC_BCY",
    "BTC_BELA",
    "BTC_BLK",
    "BTC_BTCD",
    "BTC_BTM",
    "BTC_BTS",
    "BTC_BURST",
    "BTC_CLAM",
    "BTC_DASH",
    "BTC_DCR",
    "BTC_DGB",
    "BTC_DOGE",
    "BTC_EMC2",
    "BTC_ETC",
    "BTC_ETH",
    "BTC_EXP",
    "BTC_FCT",
    "BTC_FLDC",
    "BTC_FLO",
    "BTC_GAME",
    "BTC_GNO",
    "BTC_GNT",
    "BTC_GRC",
    "BTC_HUC",
    "BTC_LBC",
    "BTC_LSK",
    "BTC_LTC",
    "BTC_MAID",
    "BTC_NAUT",
    "BTC_NAV",
    "BTC_NEOS",
    "BTC_NMC",
    "BTC_NOTE",
    "BTC_NXC",
    "BTC_NXT",
    "BTC_OMNI",
    "BTC_PASC",
    "BTC_PINK",
    "BTC_POT",
    "BTC_PPC",
    "BTC_RADS",
    "BTC_REP",
    "BTC_RIC",
    "BTC_SBD",
    "BTC_SC",
    "BTC_SJCX",
    "BTC_STEEM",
    "BTC_STR",
    "BTC_STRAT",
    "BTC_SYS",
    "BTC_VIA",
    "BTC_VRC",
    "BTC_VTC",
    "BTC_XBC",
    "BTC_XCP",
    "BTC_XEM",
    "BTC_XMR",
    "BTC_XPM",
    "BTC_XRP",
    "BTC_XVC",
    "BTC_ZEC",
    "ETH_ETC",
    "ETH_GNO",
    "ETH_GNT",
    "ETH_LSK",
    "ETH_REP",
    "ETH_STEEM",
    "ETH_ZEC",
    "USDT_BTC",
    "USDT_DASH",
    "USDT_ETC",
    "USDT_ETH",
    "USDT_LTC",
    "USDT_NXT",
    "USDT_REP",
    "USDT_STR",
    "USDT_XMR",
    "USDT_XRP",
    "USDT_ZEC",
    "XMR_BCN",
    "XMR_BLK",
    "XMR_BTCD",
    "XMR_DASH",
    "XMR_LTC",
    "XMR_MAID",
    "XMR_NXT",
    "XMR_ZEC"
]

AVAILABLE_SUBSCRIPTIONS = CURRENCY_PAIRS[:]
AVAILABLE_SUBSCRIPTIONS += [
    'footer',
    'ticker',
    'trollbox',
    'alerts',
    'heartbeat',
]
